/* include file for interp.lib					*/
/* interp.h - Copyright 1995,1996 David Weaver			*/

#ifndef INTERP_H_
#define INTERP_H_

#include "../src/interp/bob.h"
#include "../src/interp/boberr.h"
#include "../src/interp/bobodb.h"
#include "../src/interp/compiler.h"
#include "../src/interp/dfile.h"
#include "../src/interp/execute.h"
#include "../src/interp/function.h"
#include "../src/interp/linebuf.h"
#include "../src/interp/objects.h"
#include "../src/interp/osint.h"
#include "../src/interp/packet.h"
#include "../src/interp/path.h"
#include "../src/interp/streams.h"
#include "../src/interp/ver_info.h"

#endif