/*************************************************************************/
/* Name: ini_file.h			                                             */
/* Vers: 1.0                                                             */
/* Prog: David Weaver, dew118@psu.edu                                 	 */
/*                                                                       */
/* Desc: Provide structures for ini_file functions						 */                                                         */
/*                                                                       */
/* NOTE: 														         */
/*       	      					                                     */
/*                                                                       */
/* Copyright 1995,1996 David Weaver                						 */
/*                                                                       */
/*************************************************************************/

#ifndef INI_FILE_H_
#define INI_FILE_H_




#endif
 
