//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by is_slip.rc
//
#define IDS_FILTER                      101
#define IDS_SERVER                      102
#define IDS_SERVER_DEBUG                103
#define IDS_FILTER_DEBUG                104

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         103
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
